### ISSUE TITLE
Any documentation you can share?

### ISSUE THREAD

**Issue by juanmed** [davidflam/OpenMoCap#2]
Hi,

Thanks for sharing this interesting project. It is  sad that development did not continue. Since the page openmocap.org is down, I was unable to find any documentation related to the project. Do you have to still have any documents (papers, manuals, diagrams, etc) that let us know more about this project and the code? Anything will be useful for those of us interested. Thanks!

**Comment by davidflam** [comment]
Hey juanmed,

You may find some information in my [master's thesis](https://repositorio.ufmg.br/handle/1843/SLSS-7WMJG9) (unfortunately only in portuguese) and a [paper](https://ieeexplore.ieee.org/document/5479097) (in english) that I wrote in 2009. Hope that helps a bit.

Regards,

David
