### ISSUE TITLE
Does this code include a solver?

### ISSUE THREAD

**Issue by antithing** [davidflam/OpenMoCap#3]
Hi, and thanks for making this code available!
I have a moCap system that outputs 3D points as joint positions. 
What I need to do is 'solve' these positions onto a skeleton, eg: Create the joint rotations from the 3d point data.

Does this repo include the code to do this?

Thanks!

**Comment by davidflam** [comment]
Hello,

Unfortunately, this repo does not have code to fit 3d cloud points onto skeletons. It outputs data only in TRC format.

Best,

David
